#!/bin/bash

# 20180316
# Memory calculation reference
# https://unix.stackexchange.com/questions/152299/how-to-get-memory-usedram-used-using-linux-command
# 20200726
# Remove;
# - Alias                 = `echo;grep -i alias $HOME/.bash_profile | grep -v ^#`
# - Local IP Address              = `hostname -I`
# Notes:
# Command to block IP: $~ iptables -A INPUT -s 42.123.81.144 -j DROP
# Command to save iptables: $~ service iptables save
# Add - Hardware Informations
# Need to install lshw for display informations
# Update total user command

echo "
	System Status:
	Date/Time: `date`
	Total User: `w -h | wc -l`

	- Server Name			= `hostname`
	- Load Average          	= `cat /proc/loadavg`
	- System Uptime         	= `uptime | awk '{ print $3 " " $4}'`
	- Kernel Version           	= `uname -r`
	- CPU Usage             	= `grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}'` %
	- Memory Usage (Actual) 	= `free -m| awk 'FNR == 3 {print $3/($3+$4)*100}'` %
	- Memory Free (Cache)   	= `free -m | head -n 3 | tail -n 1 | awk '{print $3}'` Mb
	- Swap in use           	= `free -m | tail -n 1 | awk {'print $3'}`
	- Root Disk Space Used       	= `df -h / | awk '{ a = $3 } END { print a }'`
	- Root Disk Space Avaible    	= `df -h / | awk '{ a = $4 } END { print a }'`

	Hardware Information:
	- CPU 			= `dmidecode -t processor | grep Version | cut -d " " -f 2-`
	- Graphic		= `lshw -class display | grep product | awk '{ sub(/^[ \t]+/, ""); print }' | cut -d " " -f 2-`

"

